services:
  web:
    build: .
    command: gunicorn devops_landing.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/staticfiles
      - ./media:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
